name: todolistapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS-style
  cupertino_icons: ^1.0.8

  # Theme & State
  provider: ^6.1.2

  # Data
  shared_preferences: ^2.5.3

  # UI & Font
  google_fonts: ^6.0.0
  settings_ui: ^2.0.2
  fl_chart: ^0.68.0

  # Data processing - Time
  intl: ^0.20.2

  # ✅ Firebase - đồng bộ thế hệ mới
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3

  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

  # Calendar
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/user.png
    - assets/A1.png
    - assets/A2.png
    - assets/A3.png
    - assets/A4.png
    - assets/A5.png
    - assets/A6.png
    - assets/A7.png
    - assets/logotodolist.png
    - assets/account.png
