name: todolistapp
description: "A new Flutter project."
publish_to: 'none' # private, không publish lên pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Icon iOS-style
  cupertino_icons: ^1.0.8

  # Lưu dữ liệu cục bộ (chọn ảnh nền, theme, v.v.)
  shared_preferences: ^2.3.0
  google_fonts: ^6.0.0
  intl: ^0.19.0
  sqflite: ^2.4.2
  path: ^1.9.1

  # Thông báo cục bộ (local notification)
  flutter_local_notifications: ^17.2.1

  # Quản lý múi giờ cho notification
  timezone: ^0.9.3

  # Lấy timezone hệ thống (plugin chính thức)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/A1.png
    - assets/A2.png
    - assets/A3.png
    - assets/A4.png
    - assets/A5.png
    - assets/A6.png
    - assets/A7.png
    - assets/logotodolist.png
    - assets/account.png
